### ISSUE TITLE
Rewrite with config flow

### ISSUE THREAD

**Issue by oribafi** [doudz/homeassistant-myjdownloader#12]
Forked thread from https://github.com/doudz/homeassistant-myjdownloader/issues/6 to discuss rewrite of this integration with config flow and more platforms in https://github.com/oribafi/homeassistant-myjdownloader/tree/rewrite.

It's still in early development, so I'm grateful for feedback and anyone willing to test. Thanks for this great integration, which motivated me to learn how to write integrations for HA!

## Features

**Sensor**

- status
- number of links
- number of packages

**Binary Sensor**

- update available

**Switch**

- pause downloads
- limit download speed

**Service**

- `myjdwonloader.run_update_check`
- `myjdwonloader.restart_and_update`
- `myjdwonloader.start_downloads`
- `myjdwonloader.stop_downloads`

## Todo

- [ ] When using the pause switch, it might take a while for the status sensor to reflect the new pause state.  
I need to trigger the update of the status entity out-of-order, when the pause switch is toggled.
- [ ] There is not much error handling yet, e.g. when you change your password, you need to remove and add the integration again.  
- [x] Not tested with more than one JDownloader yet.
- [x] Devices which are not online during setup of the integration should be created when they become available.
- [x] Devices becoming offline will turn to unavilable.

**Comment by doudz** [comment]
I gave a try and :

- config flow works good !
- maybe my fault but when I added the integration my jdownloader was down, and when I start it I was expected sensor creation, etc, but nothing happens
I can't call service myjdwonloader.run_update_check or myjdwonloader.restart_and_update since no device is available (because of previous reason)

**Comment by doudz** [comment]
Same problem when I shut down my jdownloader, every sensors become unavailable (which is good) but if I start JDownloader again, components are stil unavailable
![image](https://user-images.githubusercontent.com/1262548/115835017-1f855680-a416-11eb-9d58-acfb4ad4296c.png)

**Comment by oribafi** [comment]
Great thanks for testing and good catch! We probably need to regularly update the list of available devices and dynamically create the corresponding devices. The former is straightforward, but for the latter, I need to search for examples where integrations do that.

When you shutdown and startup your JDownloader again, is there anything in the log, which mentions for example, that updates for this device are not possible anymore? Maybe HA stops us from updating our entities if we throw exceptions (due to missing device) too often?

**Comment by oribafi** [comment]
I just pushed a new version which enables the integration to reconnect to temporarily offline devices as long as they have been online during the last HA restart.

**Comment by oribafi** [comment]
@doudz I just pushed a new version which is able to add JDownloader devices as soon as they become online.

**Comment by doudz** [comment]
Looks like it works good ! :tada: 
if you're ok with it, please make a PR

**Comment by doudz** [comment]
Looks very good !
Maybe you could make it "unavailable" when JDownloader goes down again ?
![image](https://user-images.githubusercontent.com/1262548/118849261-db2f8e00-b8cf-11eb-88ef-aa06a4a10b84.png)

Good work !
If you're ok make a PR and I publish it !

**Comment by oribafi** [comment]
Thanks for giving it another try! 

I just made a fix for this unavailable behavior and the upstream maintainer was so kind to develop an improvement for exception handling for disconnected devices in [mmarquezs/My.Jdownloader-API-Python-Library#42](https://github.com/mmarquezs/My.Jdownloader-API-Python-Library/issues/42) which I am already using in my dev environment. 

I'll let you know once it's released and update the package version in the manifest.json.

**Comment by oribafi** [comment]
myjdapi 1.1.0 just got released and I updated the branch. Could you test it once again?

If this works well for you, I'll draft the pr.

**Comment by doudz** [comment]
Works good for me , you did a good work ! :clap:
